version: '3'

services:
  backend:
    build: backend/
    image: danabib/ovw-dogs-backend:latest
    ports: 
      - 8080:8080
    networks:
      - deploy_network
    container_name: backend

  frontend:
    build: frontend/
    image: danabib/ovw-dogs-frontend:latest
    depends_on:
      - backend
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: frontend

networks:
  deploy_network:
    driver: bridge