name: overweight
dependencies:
  - python==3.8
  - gunicorn
  - uvicorn
  - fastapi
  - pydantic
  - pandas
  - numpy
  - scikit-learn
  - jieba
  - pytest
  - pytest-html
  - pytorch
  - torchvision
  - torchsummary
  - efficientnet_pytorch